baseURL = "https://smyrdek.com/"
languageCode = "pl-PL"
title = "Przemek Smyrdek / Rozwijaj się! Programowanie i wiele więcej."
theme = "hugo-paper"
publishDir = "docs"
googleAnalytics = "UA-130241188-1"
canonifyURLs = true
disqusShortname = "przemeksmyrdek"
enableRobotsTXT = true

[permalinks]
    post = "/:year/:month/:title/"

[params]
    description = "Przemek Smyrdek / Rozwijaj się! Programowanie i wiele więcej."
    author = "Przemek Smyrdek"

[menu]

    [[menu.main]]
        identifier = "start"
        name = "Start"
        url = "/start/"
        weight = -110

    [[menu.main]]
        identifier = "prezentacje"
        name = "Talks"
        url = "/talks/"
        weight = -100

    [[menu.main]]
        identifier = "creativity"
        name = "Creativity"
        url = "/creativity/"
        weight = -90

    [[menu.main]]
        identifier = "video"
        name = "Video"
        url = "https://www.youtube.com/c/przeprogramowani"
        weight = -80

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = -70