baseURL = "https://smyrdek.com/"
languageCode = "pl-PL"
title = "Przemek Smyrdek / Develop Yourself"
theme = "hugo-paper"
publishDir = "docs"
googleAnalytics = "UA-130241188-1"
canonifyURLs = true
disqusShortname = "przemeksmyrdek"
enableRobotsTXT = true

[permalinks]
    post = "/:year/:month/:title/"

[params]
    description = "Przemek Smyrdek / Develop Yourself"
    author = "Przemek Smyrdek"

[menu]

    [[menu.main]]
        identifier = "about"
        name = "About me"
        url = "/about-me/"
        weight = -110

    [[menu.main]]
        identifier = "prezentacje"
        name = "Talks & Slides"
        url = "/talks/"
        weight = -100

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = -90