baseURL = "https://smyrdek.com/"
languageCode = "en-US"
title = "Develop Yourself - Helping developers grow and work better"
theme = "hugo-paper"
publishDir = "docs"
googleAnalytics = "UA-130241188-1"
canonifyURLs = true
disqusShortname = "przemeksmyrdek"
enableRobotsTXT = true

[permalinks]
    post = "/:year/:month/:title/"

[params]
    description = "Develop Yourself - Helping developers grow and work better"
    author = "Przemek Smyrdek"

[menu]

    [[menu.main]]
        identifier = "learn-more"
        name = "Learn More"
        url = "/learn-more/"
        weight = -110

    [[menu.main]]
        identifier = "public-speaking"
        name = "Speaking"
        url = "/public-speaking/"
        weight = -100

    [[menu.main]]
        identifier = "covers-and-illustrations"
        name = "Drawing"
        url = "/covers-and-illustrations/"
        weight = -90

    [[menu.main]]
        identifier = "videos"
        name = "Videos"
        url = "https://www.youtube.com/channel/UCnrmvLXGA-EX-O4aBHAlipw"
        weight = -80

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = -70