baseURL = "https://psmyrdek.github.io/blog/"
languageCode = "pl-pl"
title = "Przemek Smyrdek - Blog"
theme = "hugo-paper"
publishDir = "docs"
googleAnalytics = "UA-130241188-1"
canonifyURLs = true

[permalinks]
    post = "/:year/:month/:title/"

[params]
    description = "Przemek Smyrdek - Blog"
    author = "Przemek Smyrdek"