baseURL = "https://smyrdek.com/"
languageCode = "pl-PL"
title = "Przemek Smyrdek / Rozwijaj się! Programowanie i wiele więcej."
theme = "hugo-paper"
publishDir = "docs"
googleAnalytics = "UA-130241188-1"
canonifyURLs = true
disqusShortname = "przemeksmyrdek"
enableRobotsTXT = true

[permalinks]
    post = "/:year/:month/:title/"

[params]
    description = "Przemek Smyrdek / Rozwijaj się! Programowanie i wiele więcej."
    author = "Przemek Smyrdek"

[menu]

    [[menu.main]]
        identifier = "start"
        name = "Start"
        url = "/start/"
        weight = -110

    [[menu.main]]
        identifier = "prezentacje"
        name = "Prezentacje"
        url = "/prezentacje/"
        weight = -100

    [[menu.main]]
        identifier = "ilustracje"
        name = "Ilustracje"
        url = "/ilustracje/"
        weight = -90

    [[menu.main]]
        identifier = "filmy"
        name = "Filmy"
        url = "https://www.youtube.com/channel/UCnrmvLXGA-EX-O4aBHAlipw"
        weight = -80

    [[menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "/kontakt/"
        weight = -70