baseURL = "https://smyrdek.com/"
languageCode = "pl-pl"
title = "Przemek Smyrdek"
theme = "hugo-paper"
publishDir = "docs"
googleAnalytics = "UA-130241188-1"
canonifyURLs = true
disqusShortname = "przemeksmyrdek"

[permalinks]
    post = "/:year/:month/:title/"

[params]
    description = "Przemek Smyrdek - o rozwoju, nie tylko w programowaniu"
    author = "Przemek Smyrdek"

[menu]

    [[menu.main]]
        identifier = "about"
        name = "O mnie"
        url = "/o-mnie/"
        weight = -110

    [[menu.main]]
        identifier = "ilustracje"
        name = "Ilustracje"
        url = "/ilustracje/"
        weight = -100

    [[menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "/kontakt/"
        weight = -90

    [[menu.main]]
        identifier = "learney.io"
        name = "Learney.io"
        url = "https://www.learney.io/"
        weight = -80
