baseURL = "https://smyrdek.com/"
languageCode = "pl-pl"
title = "Przemek Smyrdek - O rozwoju, nie tylko w programowaniu"
theme = "hugo-paper"
publishDir = "docs"
googleAnalytics = "UA-130241188-1"
canonifyURLs = true
disqusShortname = "przemeksmyrdek"
enableRobotsTXT = true

[permalinks]
    post = "/:year/:month/:title/"

[params]
    description = "Blog o rozwoju z perspektywy programisty - nauka, własne doświadczenia, inspiracje"
    author = "Przemek Smyrdek"

[menu]

    [[menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/about-me/"
        weight = -110

    [[menu.main]]
        identifier = "covers"
        name = "Covers"
        url = "/covers/"
        weight = -100

    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = -90