baseURL = "https://psmyrdek.github.io/blog/"
languageCode = "pl-pl"
title = "Przemek Smyrdek - Blog"
theme = "hugo-paper"
publishDir = "docs"
googleAnalytics = "UA-130241188-1"
canonifyURLs = true
disqusShortname = "przemeksmyrdek"

[permalinks]
    post = "/:year/:month/:title/"

[params]
    description = "Przemek Smyrdek - Blog"
    author = "Przemek Smyrdek"

[menu]

    [[menu.main]]
        identifier = "about"
        name = "O mnie"
        url = "/o-mnie/"
        weight = -110

    [[menu.main]]
        identifier = "ilustracje"
        name = "Ilustracje"
        url = "/ilustracje/"
        weight = -100